apiVersion: v1
kind: Pod
metadata:
  name: hcloud-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: nfs-pvc
          mountPath: "/data"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
